/* Replace with your SQL commands */

ALTER TABLE users
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN updated_at TYPE TIMESTAMP,
ALTER COLUMN deleted_at TYPE TIMESTAMP;

ALTER TABLE todo
ALTER COLUMN created_at TYPE TIMESTAMP,
ALTER COLUMN updated_at TYPE TIMESTAMP,
ALTER COLUMN deleted_at TYPE TIMESTAMP;